version: "3.8"
name: "PHVR"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - "./.m2:/tmp/m2"

  db:
    image: mongo:5.0
    container_name: "mongodb_container"
    restart: always
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: $MONGODB_DATABASE
    ports:
      - "$MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 15s
      timeout: 5s
      retries: 3
    volumes:
      - mongo:/var/lib/mongo/data

volumes:
  mongo:

networks:
  phvr:
