spring:
  application:
    name: phvr

  data:
    mongodb:
      host: ${MONGODB_LOCAL_PORT}
      port: ${MONGODB_DOCKER_PORT}
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      database: ${MONGODB_DATABASE}


