spring:
  application:
    name: phvr

  data:
    mongodb:
      uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_LOCAL_PORT}/?authSource=admin
      authentication-database: admin
      host: ${MONGODB_HOST}
      port: ${MONGODB_LOCAL_PORT}
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      database: ${MONGODB_DATABASE}